#GET http://localhost:8080/api/v1/users
####
#GET http://localhost:8080/api/v1/facilities
####
#POST http://localhost:8080/api/v1/facilities/gyms
#Content-Type: application/json
#
#{
#  "name": "Super Fit",
#  "pricePerHour": 25.50,
#  "capacity": 50,
#  "areaInSqm": 300,
#  "hasSauna": true
#}
#
####
#POST http://localhost:8080/api/v1/clients
#Content-Type: application/json
#
#{
#  "firstName": "Jan",
#  "lastName": "Nowak",
#  "login": "jnowak"
#}


### Pobranie tokena z UserService (Logowanie)
POST http://localhost:8081/api/v1/auth/login?login=kdawid
> {%
    client.global.set("auth_token", response.body);
%}

### Odpytanie UserService za pomocą tokena
GET http://localhost:8081/api/v1/users
Authorization: Bearer {{auth_token}}

### Odpytanie RentService za pomocą TEGO SAMEGO tokena
GET http://localhost:8080/api/v1/facilities
Authorization: Bearer {{auth_token}}

### Stworzenie obiektu sportowego w RentService (wymaga autoryzacji)
POST http://localhost:8080/api/v1/facilities/gyms
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "Super Fit",
  "pricePerHour": 25.50,
  "capacity": 50,
  "areaInSqm": 300,
  "hasSauna": true
}