<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>pas06</groupId>
        <artifactId>UserService-Adapters</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>UserService-SoapAdapters</artifactId>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>pas06</groupId>
            <artifactId>UserService-ViewPorts</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>pas06</groupId>
            <artifactId>UserService-ApplicationPorts</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.cxf</groupId>
            <artifactId>cxf-spring-boot-starter-jaxws</artifactId>
            <version>4.0.4</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.cxf</groupId>
            <artifactId>cxf-rt-transports-local</artifactId>
            <version>4.0.4</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>