<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>pas06</groupId>
        <artifactId>rest-sfs-root</artifactId>
        <version>0.0.1-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>rest-sfs-user</artifactId>
    <name>rest-sfs-user</name>
    <description>SFS - User Service</description>
    <packaging>pom</packaging>

    <modules>
        <module>ApplicationCore</module>
        <module>ApplicationPorts</module>
        <module>Adapters</module>
        <module>Applications</module>
        <module>ViewPorts</module>
    </modules>

</project>